name: Dart CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      - run: flutter pub get
      - run: flutter test
      - run: flutter analyze
      - run: flutter build apk
      - run: flutter build appbundle